# Generated by Django 5.1.7 on 2025-03-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=255)),
                ('pro_dis', models.TextField()),
                ('pro_img', models.ImageField(upload_to='products_images')),
            ],
        ),
    ]
