# Generated by Django 5.1.7 on 2025-04-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroManureapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pro_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
