# Generated by Django 5.1.7 on 2025-04-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroManureapp', '0002_products_pro_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.TextField()),
                ('Pincode', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('priceperunit', models.IntegerField()),
                ('totalprice', models.IntegerField()),
            ],
        ),
    ]
