# Generated by Django 5.1.7 on 2025-04-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroManureapp', '0003_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default'),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default'),
        ),
    ]
