# Generated by Django 5.1.7 on 2025-04-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroManureapp', '0004_order_details_status_products_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='Pincode',
        ),
        migrations.AddField(
            model_name='order_details',
            name='phoneNo',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='order_details',
            name='pincode',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
