# Generated by Django 5.1.7 on 2025-04-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroManureapp', '0005_remove_order_details_pincode_order_details_phoneno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pro_img',
            field=models.ImageField(upload_to='images_products'),
        ),
    ]
