# Generated by Django 5.1.7 on 2025-04-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgroManureapp', '0006_alter_products_pro_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='product_imgurl',
            field=models.CharField(default='abcd', max_length=400),
        ),
    ]
